# _config.yml
title: 我的 Markdown 网站
description: 一个由 GitHub Actions 自动部署的静态网站。

# 定义分类和标签的链接格式
collections:
  categories:
    output: true
    permalink: /categories/:path/
  tags:
    output: true
    permalink: /tags/:path/