# _config.yml
title: 工具下载平台
description: 提供Windows工具和安卓APP下载的平台，致力于为用户提供优质、安全、实用的软件资源。

# 网站配置
baseurl: "" # 网站的子路径，如果没有则为空
url: "https://aini666.vvvv.ee" # 你的网站URL
timezone: Asia/Shanghai # 设置时区为上海

# 永久链接格式
permalink: /posts/:year/:month/:day/:title/

# 定义分类和标签的链接格式
# 注意：Jekyll内置了categories和tags系统，这里不再需要单独定义collections
# 如果需要自定义集合，请使用其他名称避免冲突

# 分页配置
paginate: 10
paginate_path: "/page:num/"

# 插件配置
plugins:
  - jekyll-paginate

# 安全设置
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 保持文件编码为UTF-8
encoding: "utf-8"

# 搜索设置
include:
  - .nojekyll
  - .gitignore
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md